{% set version = "4.0.0" %}

package:
  name: uritemplate
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/u/uritemplate/uritemplate-{{ version }}.tar.gz
  sha256: 6f4c5b093c915d269df69f291028a72dfdcaf68c8345b92e180f31daf53c4971

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - simplejson >=2.5.0

test:
  imports:
    - uritemplate

about:
  home: http://github.com/uri-templates/uritemplate-py/
  license: Apache 2.0
  license_family: Apache
  license_file: LICENSE
  summary: URI Templates
  dev_url: http://github.com/uri-templates/uritemplate-py/

extra:
  recipe-maintainers:
    - pmlandwehr
    - ocefpaf
